### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by carlmon** [buunguyen/fasterflect#14]
Hi, I like this library and would like to use it. Could you please confirm that it is Apache 2.0-licensed as noted on the Nuget page (https://www.nuget.org/packages/fasterflect/)? I do not see license details in GitHub.

**Comment by carlmon** [comment]
I found Apache 2.0 noted in source code. Would you please consider tagging it at a repository level?

**Comment by buunguyen** [comment]
Yes, it's Apache 2.0. I've added the LICENSE file.

**Comment by carlmon** [comment]
Thanks for your fast response, and for the great library!
