### ISSUE TITLE
Need documentation ported over from CodePlex

### ISSUE THREAD

**Issue by cubanx** [buunguyen/fasterflect#2]
I'm happy to help move the documentation from CodePlex over.

I started here: https://github.com/cubanx/fasterflect/wiki

But, you cannot pull request wiki's so I don't really want to continue on that alone...

**Comment by buunguyen** [comment]
Thanks for offering to help. I suggest you move the docs to README.md and other markdown files directly in the repo. No need to use Wiki (I'll disable it).

**Comment by cubanx** [comment]
It's already disabled :)

Out of curiosity why not use the wiki?

If you look at my link, it formats really nicely...

**Comment by cubanx** [comment]
I've already ported over 4 of the pages...

**Comment by buunguyen** [comment]
Oh, sorry, I didn't know you already started. I'd prefer the markdown as more people can help with the doc by submit PRs. If you want to stick with wiki, I can add you as collaborator so that you can edit it directly. Let me know.

**Comment by cubanx** [comment]
Buu,

It’s your show, I can do it either way 😊

I don’t know what we lose by having the wiki directly in the repo as opposed to the standard place at /wiki

I do know your way of having it directly in the repo facilitates external pull requests.

The “standard” wiki way let’s us use all the tooling built up around wiki’s like the built in markdown editor with preview, etc.

If you forced me to pick now, just make me a collaborator, even a temporary one, so I can get it off of Codeplex ASAP 😊

Let me know either way, thanks for the quick response!

Ricardo

**Comment by buunguyen** [comment]
Oops, as I enable wiki, I just learn there's an option to allow any GitHub users to update, no need to have to be collaborator. Let me know if you have any problem adding contents to the wiki.

**Comment by cubanx** [comment]
Awesome!

I’ll move over what I’ve got from my fork fairly soon, and keep doing the CodePlex => GitHub translations as time allows.

Thanks for writing this, I’ve used Fasterflect at every job I’ve been at since you wrote it 😊

Don’t want it to go down with CodePlex!

Ricardo

**Comment by buunguyen** [comment]
> Thanks for writing this, I’ve used Fasterflect at every job I’ve been at since you wrote it 😊

Awesome!!

Thanks again for offering to help with the documentation, I really appreciate that. Really look forward to seeing the wiki moved here for good.

I'm closing this issue now.

**Comment by cubanx** [comment]
I've moved over all the pages I could find on the front page of the CodePlex docs. If there are docs that are **not** on the front page of CodePlex, I've most likely missed them :)

**Comment by buunguyen** [comment]
It looks great. I think that's everything. Totally awesome work, thank you!
